### ISSUE TITLE
https://jqplay.org/ down?

### ISSUE THREAD

**Issue by pmmalinov01** [owenthereal/jqplay#131]
It seems the website has gone down. Is this project still worked on or it is something else?

**Comment by runofthemill** [comment]
Not mine, but found https://jqkungfu.com/ as an alternative

**Comment by MarauderOne** [comment]
Love this tool, would love to see it back up and running again.

**Comment by mitin001** [comment]
Another alternative: https://sandbox.bio/playgrounds?id=jq supports raw input and other flags.

**Comment by robeberhardt** [comment]
I just downloaded the project and ran locally, it's working great and you can customize the css as well <3

**Comment by JackW6809** [comment]
I have gone ahead and span up JQ Play, if anyone wants to make use of it they can. Running their source code so the familiar UI we all know and love. :) https://jqplay.jackoxi.systems/

**Comment by Mikle-Bond** [comment]
As an effort to keep good tools alive, I've brought up https://jqplay.ter224.duckdns.org and https://jqkungfu.ter224.duckdns.org. Just in case you'll need yet another instance.

**Comment by owenthereal** [comment]
Sorry for the late response. jqplay.org is back now. The reason was due to the underlying server provider.
