### ISSUE TITLE
Feature request: Publish public Docker images to GHCR

### ISSUE THREAD

**Issue by loganmarchione** [owenthereal/jqplay#139]
I'm trying to self-host jqplay in my homelab, this tool is super-valuable! I currently have it running using the included [docker-compose file](https://github.com/owenthereal/jqplay/blob/master/docker-compose.yml).

However, my dependency management tool (Renovatebot) won't pick up new versions of jqplay because there are no public container images published. Publishing a container image would increase accessibility of jqplay to users because they wouldn't need to build the container image (which can be slow). Instead, they would simply run a pre-built container image.

My request is for you to publish public Docker images of jqplay to GitHub Container Registry (GHCR). It seems to be as simple as enabling a GitHub Action, as shown [here](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages). Then, you could update the docker-compose file to point to that image, instead of using the `build` argument.

**Comment by loganmarchione** [comment]
I see you already have a [GitHub Action that does this](https://github.com/owenthereal/jqplay/blob/master/.github/workflows/build.yml), but I'm not seeing any [packages](https://github.com/owenthereal?tab=packages&repo_name=jqplay).  Are they not public?

**Comment by owenthereal** [comment]
Yes https://github.com/owenthereal/jqplay/pkgs/container/jqplay
