### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by diceone** [owenthereal/jqplay#74]
docker build -t jqplay . produces:

Removing intermediate container d3df0807b5e5
Step 4/8 : ADD . $GOPATH/src/github.com/jingweno/jqplay
 ---> b7c56fefd4d9
Step 5/8 : WORKDIR $GOPATH/src/github.com/jingweno/jqplay
 ---> a75ebd268fa3
Removing intermediate container 0ddb40fa3277
Step 6/8 : RUN bin/build
 ---> Running in dd20753b0273
 github.com/jingweno/jqplay/server
server/server.go:83: srv.Shutdown undefined (type *http.Server has no field or method Shutdown)
The command '/bin/sh -c bin/build' returned a non-zero code: 2

**Comment by loganmarchione** [comment]
@diceone @sammcj  - Is this still an issue? You should be able to run `make start` which is the equivalent of running `docker-compose up --build --force-recreate` and then jqplay should be available at [`http://localhost:8080/`](http://localhost:8080/).
