### ISSUE TITLE
Null input checkbox doesn't work

### ISSUE THREAD

**Issue by enolan** [owenthereal/jqplay#76]
It seems to be completely ignored. To reproduce:

- Enter `{}` in the filter box
- Check "Null Input". Nothing appears in the output box
- Enter `null` in the input box. `{}` appears in the output box, as expected.

Running `jq --null-input '{}'` on the command line outputs `{}` as expected.

**Comment by zstadler** [comment]
Any content in the **JSON** box would trigger the jq evaluation, including a space character
