### ISSUE TITLE
multiline input please?

### ISSUE THREAD

**Issue by bukzor** [owenthereal/jqplay#77]
I'd like to run a longer jq script, but the one-line input field is very unweildy for that.
Replacing the `input` with `textarea` should do the trick. It can even be the same size, but then I can resize it myself.

**Comment by ErmineII** [comment]
Additionally, this should make it monospace (which I was considering suggesting too)

**Comment by owenthereal** [comment]
This is done in https://github.com/owenthereal/jqplay/pull/124.
