### ISSUE TITLE
JQPlay site busted

### ISSUE THREAD

**Issue by geofffox** [owenthereal/jqplay#95]
I'm sorry to say (because I use it), the site is up but not responding with the proper web code.

**Comment by Youboontoo** [comment]
I can confirm this as well. I'm on Brave Browser `Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)`. Below is a screenshot of what I see, even with Brave's shields down.
![image](https://user-images.githubusercontent.com/16302135/70396943-60680100-19c2-11ea-811d-a3df875a57ba.png)

**Comment by loganmarchione** [comment]
@geofffox can we close it this out? The site is working for me.

https://jqplay.org/

**Comment by geofffox** [comment]
Thank you, Owen.

Geoff
